# Generated by Django 4.2.7 on 2023-12-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graphic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_chartType', models.CharField(max_length=20)),
                ('cur_dataTable', models.CharField(max_length=200)),
                ('more', models.CharField(max_length=100)),
                ('cur_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=30)),
                ('object_type', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('foto_link', models.CharField(max_length=30)),
            ],
        ),
    ]
